export function getCountryImg(countryRegion) {
  const data = {
    "China": "https://i.pinimg.com/564x/a2/b1/c0/a2b1c00569a01fb123880b0543964f96.jpg",
    "Italy": "",
    "Iran": "",
    "Korea South": "",
    "Spain": "",
    "Germany": "",
    "France": "",
    "US": "",
    "Switzerland": "",
    "United Kingdom": "",
    "Norway": "",
    "Sweden": "",
    "Netherlands": "",
    "Denmark": "",
    "Japan": "",
    "Cruise Ship": "",
    "Belgium": "",
    "Austria": "",
    "Qatar": "",
    "Canada": "",
    "Australia": "",
    "Malaysia": "",
    "Greece": "",
    "Finland": "",
    "Singapore": "",
    "Bahrain": "",
    "Israel": "",
    "Czechia": "",
    "Slovenia": "",
    "Portugal": "",
    "Iceland": "",
    "Brazil": "",
    "Ireland": "",
    "Romania": "",
    "Estonia": "",
    "Philippines": "",
    "Iraq": "",
    "Egypt": "",
    "Kuwait": "",
    "Saudi Arabia": "",
    "Poland": "",
    "India": "",
    "Indonesia": "",
    "Lebanon": "",
    "United Arab Emirates": "",
    "Thailand": "",
    "San Marino": "",
    "Chile": "",
    "Russia": "",
    "Taiwan*": "",
    "Vietnam": "",
    "Luxembourg": "",
    "Serbia": "",
    "Slovakia": "",
    "Bulgaria": "",
    "Brunei": "",
    "Albania": "",
    "Peru": "",
    "South Africa": "",
    "Croatia": "",
    "Algeria": "",
    "Panama": "",
    "Argentina": "",
    "Pakistan": "",
    "Hungary": "",
    "Georgia": "",
    "Ecuador": "",
    "Belarus": "",
    "Costa Rica": "",
    "Mexico": "",
    "Cyprus": "",
    "Latvia": "",
    "Colombia": "",
    "Oman": "",
    "Bosnia and Herzegovina": "",
    "Armenia": "",
    "Malta": "",
    "Tunisia": "",
    "Morocco": "",
    "Azerbaijan": "",
    "North Macedonia": "",
    "Moldova": "",
    "Afghanistan": "",
    "Dominican Republic": "",
    "Maldives": "",
    "Bolivia": "",
    "Senegal": "",
    "Sri Lanka": "",
    "Martinique": "",
    "Lithuania": "",
    "Jamaica": "",
    "Cambodia": "",
    "New Zealand": "",
    "Reunion": "",
    "Kazakhstan": "",
    "Paraguay": "",
    "Turkey": "",
    "Cuba": "",
    "Liechtenstein": "",
    "Uruguay": ""
  };

  return data[countryRegion];
}